version: '3'
services:
    php74:
        build: ./php74
        environment:
            - MYSQL_SOCKET:/var/run/mysqld/mysqld.sock
        volumes:
            - .:/git/Laravel7Trainning
            - ./php74/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - ./php74/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - php-fpm:/var/run/php-fpm
            - mysql:/var/run/mysqld
    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - .:/git/Laravel7Trainning
            - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - php-fpm:/var/run/php-fpm
        depends_on:
            - php74
    mysql:
        build: ./mysql
        ports:
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: mypass
            MYSQL_USER: mysqluser
            MYSQL_PASSWORD: mysqlpass
            MYSQL_DATABASE: docker_trainning
            TZ: 'Asia/Tokyo'
        volumes:
            - .:/git/Laravel7Trainning
            - ./mysql/conf/default_authentication.cnf:/etc/mysql/conf.d/default_authentication.conf
            - ./mysql/sql:/docker-entrypoint-initdb.d
            # - ./mysql/data:/var/lib/mysql
            - mysql:/var/run/mysqld
volumes:
    mysql:
    php-fpm:

